
# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.6

# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED 1

# Command to install spaCy
RUN pip install spacy==2.0.11 https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.0.0/en_core_web_lg-2.0.0.tar.gz


# create root directory for our project in the container
RUN mkdir /affect

# Set the working directory
WORKDIR /affect

# Copy the current directory contents into the container
ADD . /affect

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
