# Generated by Django 2.1.3 on 2018-11-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20181115_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
