# Generated by Django 2.1.2 on 2018-12-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20181215_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scotch',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scotch',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
