# Generated by Django 2.1.2 on 2018-12-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20181216_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionscotchsimilarity',
            name='similarity',
            field=models.TextField(blank=True),
        ),
    ]
